@startmindmap

* hidden layer
** out layer
***_ outVec

left side

**_ inVec


legend
8x8 bits images of number 0-9. 11 training examples.
64 signals (in), 15 neurons (hidden), 10 neurons (out))
Sigmoid activation function
LEARNING_RATE = 0.01
end legend


@endmindmap