@startmindmap

* hidden layer
** hidden layer
*** out layer
****_ outVec

left side

**_ inVec


legend

The data set consists of 50 samples from each of three
species of Iris (Iris setosa, Iris virginica and Iris
versicolor). Four features were measured from each
sample: the length and the width of the sepals and petals,
in centimeters. Based on the combination of these four features,
Fisher developed a linear discriminant model to distinguish the
species from each other.

4 signals (in), 10 neurons (hidden), 10 neurons (hidden), 3 neurons (out))
Sigmoid activation function
LEARNING_RATE = 0.01
end legend


@endmindmap