
@startuml
'https://plantuml.com/class-diagram


interface StateInterface<V=generic state variables> {
+ V getVariables();
+ set(StateInterface<V> state);
}




interface TrainerInterface<V=generic state variables> {
+ train()
}

abstract class TrainerAbstract {
TrainingTracker tracker
TrainerParameters parameters
}

abstract class TrainerAbstractTBD {
    EnvironmentInterface<<V>> environment;
    Agent<<V>> agent;
}

interface EnvironmentInterface<V=generic state variables> {
+  StepReturn<<V>> step(StateInterface<<V>> state,int action);
'/ +  boolean isTerminalState(StateInterface<<V>> state);
}


EnvironmentInterface <|-- Environment1
EnvironmentInterface <|-- Environment2

TrainerInterface <|-- TrainerAbstract
TrainerAbstract <|-- TrainerAbstractTBD
TrainerAbstractTBD  <|-- Trainer1
TrainerAbstractTBD  <|-- Trainer2

StateInterface -[hidden]- EnvironmentInterface
Environment1 -[hidden]- TrainerInterface


@enduml