@startuml

object 0
object 1
object 2
object 3
object 4
object 5
5 : split
object 6
object 7
object 8
object 9
object 10
10 : heaven (+10)
object 11
object 12
object 13
object 14
object 15
15 : hell (-10)


0 -right-> 1
1 -right-> 2
2 -right-> 3
3 -right-> 4
4 -right-> 5
5 -down-> 6
5 -right-> 7
7 -right-> 8
8 -right-> 9
9 -right-> 10
6 -down-> 11
11 -down-> 12
12 -down-> 13
13 -down-> 14
14 -down-> 15


object ActionSpace #grey
ActionSpace : 2 per state
ActionSpace -up[hidden]-> 3

object Transition #grey
Transition : higher number for all actions except split
Transition -up[hidden]-> 8

object Reward #grey {
R_HELL if moving to state 15
R_HEAVEN if moving to state 10
R_MOVE else
           }
Reward -up[hidden]-> Transition


@enduml
