@startuml
'https://plantuml.com/class-diagram

interface AgentInterface {
+ int chooseAction(double probRandom)
+ updateState(StepReturn stepReturn);
+ double readValue(int state);
}

interface AgentNeuralInterface {
+ learn(List<NstepExperience> miniBatch);
}

interface EnvironmentInterface {
+  StepReturn step(int state,int action);
+  boolean isTerminalState(int state);
}


abstract class AgentAbstract {
    EnvironmentInterface environment;
    int state;
}


class AgentForkNeural {
NetworkMemoryInterface memory;
}
class AgentForkTabular  {
Map<Integer, Double> memory;
}
class ForkEnvironment
class MazeEnvironment


AgentInterface <|-- AgentNeuralInterface

AgentInterface <|-- AgentAbstract
AgentNeuralInterface <|-- AgentForkNeural
AgentInterface <|-- AgentForkTabular
AgentAbstract <|-- AgentForkNeural
AgentAbstract <|-- AgentForkTabular

EnvironmentInterface <|-- ForkEnvironment
EnvironmentInterface <|-- MazeEnvironment

AgentAbstract  o-- ForkEnvironment
AgentAbstract  o-- MazeEnvironment





@enduml